apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/server*.log
      tags: ["json"]
      enabled: true
      reload.enabled: true
      reload.period: 10s
      client_inactivity_timeout: 12000
      processors:
        - drop_event.when.regexp.message: '"[lL]evel"\s*:\s*"accounting"'
    - type: container
      paths:
        - /var/log/containers/server*.log
      tags: ["accounting"]
      enabled: true
      reload.enabled: true
      reload.period: 10s
      client_inactivity_timeout: 12000
      processors:
        - drop_event.when.not.regexp.message: '"[lL]evel"\s*:\s*"accounting"'
    - type: container
      paths:
        - /var/log/containers/celery*.log
      tags: ["json"]
      enabled: true
      reload.enabled: true
      reload.period: 10s
      client_inactivity_timeout: 12000
      processors:
        - drop_event.when.regexp.message: '"[lL]evel"\s*:\s*"accounting"'
    - type: container
      paths:
        - /var/log/containers/celery*.log
      tags: ["accounting"]
      enabled: true
      reload.enabled: true
      reload.period: 10s
      client_inactivity_timeout: 12000
      processors:
        - drop_event.when.not.regexp.message: '"[lL]evel"\s*:\s*"accounting"'
    output.logstash:
      bulk_max_size: 10
      client_inactivity_timeout: 12000
      ssl.enabled: true
      hosts: <your-host>
      ssl.certificate_authorities: <your-ca-file>
      ssl.certificate: <your-cert-file>
      ssl.key: <your-key-file>
