apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*server*.log
      tags: ["json"]
      enabled: true
      reload.enabled: true
      reload.period: 10s
      client_inactivity_timeout: 12000
    - type: container
      paths:
        - /var/log/containers/server*.log
      tags: ["accounting"]
      enabled: true
      reload.enabled: true
      reload.period: 10s
      processors:
        - drop_event.when.not.regexp.message: '"[lL]evel"\s*:\s*"accounting"'
    output.logstash:
      bulk_max_size: 10
      client_inactivity_timeout: 12000
      ssl.enabled: true
      hosts: ["loggingaggregator.dev.neanias.eu:31314"]
      ssl.certificate_authorities: ["/etc/filebeat/ca/neanias-ca-bundle.crt"]
      ssl.certificate: "/etc/filebeat/certificates/lse-devel.crt"
      ssl.key: "/etc/filebeat/certificates/lse-devel.key"