apiVersion: skaffold/v2beta22
kind: Config
profiles:
    - name: local
      activation:
          - kubeContext: minikube
      build:
          local:
              push: true
          tagPolicy:
              sha256: {}
          artifacts:
              - image: server
                context: server/
                docker:
                    dockerfile: ./dockerfiles/server/Dockerfile.local
                    noCache: False
                sync:
                    infer:
                        - "**/*"
              - image: celery
                context: server/
                docker:
                    dockerfile: ./dockerfiles/celery/Dockerfile.local
                    noCache: False
                sync:
                    infer:
                        - "**/*"
              - image: client
                context: client/
                docker:
                    dockerfile: ./dockerfiles/Dockerfile.local
                    noCache: False
                sync:
                    infer:
                        - "**/*"
      deploy:
          kubectl:
              manifests:
                  - ./queue/k8s/local/*
                  - ./server/k8s/server/local/*
                  - ./server/k8s/celery/local/*
                  - ./client/k8s/local/*
                  #- ./filebeat/k8s/local/*
